version: "3.3"
services:
  which-boob-bot:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"  # Маппинг портов: порт хоста:порт контейнера
    volumes:
      - .:/app  # Монтируем текущую директорию в /app внутри контейнера
    environment:
      - YOUR_BOT_TOKEN=${YOUR_BOT_TOKEN}

